### PR TITLE
Topology edits

### PR DESCRIPTION
**Pull request by EZsemlye**
Should be two files to review, with descriptions of the changes made to each version

### CODE REVIEW

**Comment by zlotty** [comment]
@jzornow @merryt these commits are the big topology cleanup from @EZsemlye. What should the process be for merging these relative to Tyler's fixed conversion of the KML files to GeoJSON? Do we accept Tyler's stuff first and then Erik's?

**Comment by merryt** [comment]
So far there isn't any overlap!

**Comment by EZsemlye** [comment]
Sorry it's taken me a couple of days to get to this.

I hope I've done this correctly. The only way I know to commit the changes
using files on GitHub is to use the GitHub Desktop app and Windows
Explorer. Since the folder on my computer is a copy of what is on the repo
on GitHub, the folder already contained a copy of the original file
("1-bikestreets-master-v0.3.geojson"), I had to delete that one in order to
put the updated file in the folder (Windows Explorer won't allow for two
files with the same name in the same folder).

Let me know if it's showing up properly in the pull request now. Cheers,

Erik

**Comment by merryt** [comment]
That is perfect! Everything you described sounds right!

Sorry if I am over explaining.

there are kinda to mirrored instances of the repo. one on your computer called "local" and one on github called "origin". In each repo there are "branches". On both your local, and origin there are branches called `topology-edits`. I think your local branch has a commit with these updates in it that hasn't made it to origin (the server) yet, is there anyway you could you push those changes @EZsemlye! The last time you pushed updates to this branch was 8 days ago.

Again, sorry if I am explaining something you already know.

**Comment by EZsemlye** [comment]
I understand the part about the mirrored folders, I just couldn't remember
how I had committed the changes the first time around.

I tried an alternate method of just uploading the new file on the GitHub
website. In order to do that, I created another new branch to hold the new
file and commit the change to the master branch.

On the desktop app, the button to commit the changes was grayed out, which
is what was preventing me from committing. It wasn't until I re-visited the
app that I noticed that I was required to provide a summary of the commit
(see attached screenshot). Once I did that I was able to commit the changes
to the topology-edits branch.

As a result, I think I've submitted the same change to the repo in two
different ways. Sorry for any confusion, I'm still getting the hang of
GitHub. Take a look and let me know which of the two methods seems like the
best way to go about this, and feel free to delete any superfluous files.
Hope I haven't created a mess!

Erik

**Comment by merryt** [comment]
hehe, no pressure! A joy of this project is everyone is getting to learn new things! so I hope you aren't feeling to frustrated and are getting a chance to learn a bit about github!

Sadly 😂 you aren't creating much of a mess, it doesn't look like any of these files are uploading! So nothin Lets do a screenshare sometime this week so I can see how you are doing things and maybe give you some tips for an easier workflow, hit me up on slack to work out a time!

**Comment by EZsemlye** [comment]
Hey Avi et al,

You may have noticed from GitHub notifications, but Tyler walked me through
the process, and we are all good to go with the updated files on the repo!

Erik

**Pull request merged**
